In [1]:
import pandas as pd
import numpy as np
import matplotlib as lib

In [2]:
dataset=pd.read_csv("CKD.csv")
dataset

,age,blood presure,specific gravity,albumin,sugar,rbc,pus cell,pus cell clumps,bacteria,blood glucose random,...,packet cell valume,white blood cell count,red blood cell count,hypertension,diabetes mellitus,coronary artery disease,appetite,pedal edema,anemea,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

,age,blood presure,albumin,sugar,blood glucose random,blood urea,serum creatinine,sodium,pottassium,hrmo,...,pus cell_normal,pus cell clumps_present,bacteria_present,hypertension_yes,diabetes mellitus_yes,coronary artery disease_yes,appetite_yes,pedal edema_yes,anemea_yes,classification_yes
0,2.000000,76.459948,3,0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2,0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1,0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1,0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0,0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0,0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0,2,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3,0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0,0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0,0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
dataset.columns

Index(['age', 'blood presure', 'albumin', 'sugar', 'blood glucose random',
       'blood urea', 'serum creatinine', 'sodium', 'pottassium', 'hrmo',
       'packet cell valume', 'white blood cell count', 'red blood cell count',
       'specific gravity_b', 'specific gravity_c', 'specific gravity_d',
       'specific gravity_e', 'rbc_normal', 'pus cell_normal',
       'pus cell clumps_present', 'bacteria_present', 'hypertension_yes',
       'diabetes mellitus_yes', 'coronary artery disease_yes', 'appetite_yes',
       'pedal edema_yes', 'anemea_yes', 'classification_yes'],
      dtype='object')

In [5]:
independent=dataset[['age', 'blood presure', 'albumin', 'sugar', 'blood glucose random',
       'blood urea', 'serum creatinine', 'sodium', 'pottassium', 'hrmo',
       'packet cell valume', 'white blood cell count', 'red blood cell count',
       'specific gravity_b', 'specific gravity_c', 'specific gravity_d',
       'specific gravity_e', 'rbc_normal', 'pus cell_normal',
       'pus cell clumps_present', 'bacteria_present', 'hypertension_yes',
       'diabetes mellitus_yes', 'coronary artery disease_yes', 'appetite_yes',
       'pedal edema_yes', 'anemea_yes']]

In [6]:
dependent=dataset[['classification_yes']]

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report

# Standardizing the training and test data
sc = StandardScaler()
x_train = sc.fit_transform(x_train)  # Fit and transform the training data
x_test = sc.transform(x_test)        # Transform the test data (no fitting)

# Defining the hyperparameter grid
param_grid = {
    'n_estimators': [50, 100, 150],         # Number of boosting stages
    'learning_rate': [0.01, 0.1, 0.2],     # Shrinkage rate
    'max_depth': [3, 4, 5],                # Maximum depth of individual estimators
    'subsample': [0.8, 1.0],               # Fraction of samples used for training each tree
    'min_samples_split': [2, 5, 10]        # Minimum samples required to split an internal node
}

# Initializing the Gradient Boosting Classifier
classifier = GradientBoostingClassifier()

# Initializing GridSearchCV
grid_search = GridSearchCV(
    estimator=classifier, 
    param_grid=param_grid, 
    cv=5,                      # 5-fold cross-validation
    scoring='accuracy',        # Evaluation metric
    verbose=1,                 # Display progress
    n_jobs=-1                  # Use all available cores
)

# Fitting GridSearchCV to the training data
grid_search.fit(x_train, y_train)

# Best hyperparameters
print("Best Hyperparameters:")
print(grid_search.best_params_)

# Training the best estimator on the training data
best_classifier = grid_search.best_estimator_

# Making predictions on the test set
y_pred = best_classifier.predict(x_test)

# Calculating the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Displaying the confusion matrix
print("\nConfusion Matrix:")
print(cm)

# Adding a classification report for detailed metrics
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Fitting 5 folds for each of 162 candidates, totalling 810 fits

C:\Users\sadiq\anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Best Hyperparameters:
{'learning_rate': 0.2, 'max_depth': 3, 'min_samples_split': 2, 'n_estimators': 150, 'subsample': 1.0}

Confusion Matrix:
[[45  0]
 [ 0 75]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        45
           1       1.00      1.00      1.00        75

    accuracy                           1.00       120
   macro avg       1.00      1.00      1.00       120
weighted avg       1.00      1.00      1.00       120

In [9]:
import pickle
filename="chronic_disease_prediction.sav"
pickle.dump(grid_search,open(filename,'wb'))
# Function to get user input
def get_user_input():
    print("Enter the following details for CKD prediction:")
    
    age = float(input("Age: "))
    blood_pressure = float(input("Blood Pressure: "))
    albumin = float(input("Albumin: "))
    sugar = float(input("Sugar: "))
    blood_glucose_random = float(input("Blood Glucose Random: "))
    blood_urea = float(input("Blood Urea: "))
    serum_creatinine = float(input("Serum Creatinine: "))
    sodium = float(input("Sodium: "))
    potassium = float(input("Potassium: "))
    hemoglobin = float(input("Hemoglobin: "))
    packed_cell_volume = float(input("Packed Cell Volume: "))
    white_blood_cell_count = float(input("White Blood Cell Count: "))
    red_blood_cell_count = float(input("Red Blood Cell Count: "))
    
    # For specific gravity, assume user enters one of the options (b, c, d, e)
    specific_gravity_b = int(input("Specific Gravity (b): (0 or 1) "))
    specific_gravity_c = int(input("Specific Gravity (c): (0 or 1) "))
    specific_gravity_d = int(input("Specific Gravity (d): (0 or 1) "))
    specific_gravity_e = int(input("Specific Gravity (e): (0 or 1) "))
    
    # For other binary features
    rbc_normal = int(input("Red Blood Cells Normal (0 or 1): "))
    pus_cell_normal = int(input("Pus Cell Normal (0 or 1): "))
    pus_cell_clumps_present = int(input("Pus Cell Clumps Present (0 or 1): "))
    bacteria_present = int(input("Bacteria Present (0 or 1): "))
    hypertension_yes = int(input("Hypertension (Yes: 1, No: 0): "))
    diabetes_mellitus_yes = int(input("Diabetes Mellitus (Yes: 1, No: 0): "))
    coronary_artery_disease_yes = int(input("Coronary Artery Disease (Yes: 1, No: 0): "))
    appetite_yes = int(input("Appetite (Yes: 1, No: 0): "))
    pedal_edema_yes = int(input("Pedal Edema (Yes: 1, No: 0): "))
    anemia_yes = int(input("Anemia (Yes: 1, No: 0): "))
    
    # Return all inputs as a numpy array in the correct format for prediction
    return np.array([[age, blood_pressure, albumin, sugar, blood_glucose_random,
                       blood_urea, serum_creatinine, sodium, potassium, hemoglobin,
                       packed_cell_volume, white_blood_cell_count, red_blood_cell_count,
                       specific_gravity_b, specific_gravity_c, specific_gravity_d,
                       specific_gravity_e, rbc_normal, pus_cell_normal,
                       pus_cell_clumps_present, bacteria_present, hypertension_yes,
                       diabetes_mellitus_yes, coronary_artery_disease_yes, appetite_yes,
                       pedal_edema_yes, anemia_yes]])

# Get input from user
input_features = get_user_input()


pre_input=sc.transform(input_features)
load_model=pickle.load(open("chronic_disease_prediction.sav",'rb'))
result=load_model.predict(pre_input)

Enter the following details for CKD prediction:

Age:  2
Blood Pressure:  76.45
Albumin:  3
Sugar:  0
Blood Glucose Random:  148.11
Blood Urea:  57.45
Serum Creatinine:  3.077
Sodium:  137.52
Potassium:  4.627
Hemoglobin:  12.518
Packed Cell Volume:  38.25
White Blood Cell Count:  8408.44
Red Blood Cell Count:  4.7055
Specific Gravity (b): (0 or 1)  1
Specific Gravity (c): (0 or 1)  0
Specific Gravity (d): (0 or 1)  1
Specific Gravity (e): (0 or 1)  1
Red Blood Cells Normal (0 or 1):  0
Pus Cell Normal (0 or 1):  0
Pus Cell Clumps Present (0 or 1):  0
Bacteria Present (0 or 1):  0
Hypertension (Yes: 1, No: 0):  0
Diabetes Mellitus (Yes: 1, No: 0):  0
Coronary Artery Disease (Yes: 1, No: 0):  0
Appetite (Yes: 1, No: 0):  1
Pedal Edema (Yes: 1, No: 0):  1
Anemia (Yes: 1, No: 0):  0

C:\Users\sadiq\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [10]:
result

array([1])